//------------------------------------------------------------------------
// Copyright(c) 2025 Anis Dadou (GullDSP)
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringPluginName		"Circulate Pro"
#define stringControllerName	"Circulate Pro Controller"
#define stringOriginalFilename	"Circulate.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Circulate Pro VST3 (64Bit)"
#else
#define stringFileDescription	"Circulate Pro VST3"
#endif
#define stringCompanyName		"GullDSP\0"
#define stringLegalCopyright	"Copyright(c) 2025"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
